### ISSUE TITLE
'test.aria.widgets.form.autocomplete.errorhandling.AutoComplete2' fails on all IE

### ISSUE THREAD

**Issue by lsimone** [ariatemplates/ariatemplates#1403]
A synchronization issue make the test fail;
@fbasso could explain more in detail

**Comment by fbasso** [comment]
This is the simple scenario to reproduce the issue : 

* In an autocomplete with freeText set to false, start typing a value in order to open some suggestions,
* Without selecting any value in the dropdown list, click outside the autocomplete,
* The autocomplete is expected to be in error, which is not the case on IE.

The issue come from :
* On aria.widgets.form.TextInput._dom_onblur , the checkValue is run only if this._keepFocus is false,
*  this._keepFocus is set to false in aria.widgets.form.DropDownTrait_afterDropdownClose,
* aria.popups.Popup.closeOnMouseClick run the close method, which will finally run afterDropdownClose.

The issue is that in IE, the close method is run asynchronously (to manage some other issues), which means that _dom_onblur is run before setting back _keepFocus to false.
