### ISSUE TITLE
Input field not highlighted on error.

### ISSUE THREAD

**Issue by gwbrown1968** [ariatemplates/ariatemplates#1434]
Hi, I work within Amadeus in Rail IT and we are seeing an issue where input fields that are in error are not highlighted with a red border when submit is triggered by an accelerator key. This only happens when the field being flagged in error has focus. Here are some example screenshots:

Before: Destination field has focus:
![error1](https://cloud.githubusercontent.com/assets/11675469/6863119/d54b7866-d49f-11e4-96e3-5fadc8ed68dc.png)
After 1: Clicking the Search button leads to the error popup being displayed and the field and label being highlighted in red: 
![error2](https://cloud.githubusercontent.com/assets/11675469/6863140/2b265d1e-d4a0-11e4-8a68-e32497c8c21f.png)
After 2: Using the accelerator keys Alt-Shift-S to do the search leads to the error popup being displayed, but the field and label are not highlighted in red.
![error3](https://cloud.githubusercontent.com/assets/11675469/6863193/e893ad48-d4a0-11e4-819e-b2d02664dfb3.png)

We are using Aria Templates version 1.7.1. The issue occurs on all browsers. 

The destination field is an aria AutoComplete widget but the same error occurs on a DatePicker widget. In our code the destination field has a Mandatory validator set as follows:
*dataUtils.setValidator(searchFields, "destinationStnCd", new Mandatory(this.properties.getProperty("errors.availability.noDestinationStationSelected")));*

The accelerator keys are set via the NavigationManager:
*NavigationManager.addGlobalKeyMap({key : "S", alt : true, shift : useShift, callback : {fn : "doSearch", scope : moduleCtrl}});*

Could someone please investigate this error and let me know if you need any more information.

Thanks
Graeme Brown

**Comment by divdavem** [comment]
Hi Graeme,

I have investigated the issue.

Here is what happens:
- the field is focused
- the user presses Alt-Shift-S
- `doSearch` is called
- from `doSearch`, `aria.utils.Data.validateModel` is called
- errors are correctly set on all fields by `validateModel`, including to
the focused field
- `doSearch` checks if there is any error, and, as there is at least one, it triggers the display of the modal dialog
- when the modal dialog is displayed, the field is blurred to give the focus to the button inside the dialog
- as part of the blur process on the field, the error is removed from the field. This is the normal behavior of fields in error for which no validation happens on blur, so that the user does not think the entry is wrong when it was simply not validated. Maybe we should check whether the value was modified and only remove the error in that case, that is a possibility.

However, I think that the root cause of the problem is the fact that the validation happens while the field is focused.
Doing the validation while the field is focused triggers another issue: if the user has typed something in the field just before pressing Alt-Shift-S, what is in the field is not yet in the data model and is not taken into account during the validation, because the content of the data model is updated only on blur.

So, the solution is to blur any field before doing the validation.

You can do so by executing the following code just before your `doSearch` function is called:

```js
    if (document.activeElement) {
        document.activeElement.blur();
    }
```

It should solve the issue.

Best regards,

David-Emmanuel
